import { ok, type Result } from "../result.ts";
import type {
  MaterialProvider,
  MaterialProviderFailure,
  MaterialProviderRequest,
  MaterialProviderResult,
  RedactedProviderRequest,
} from "./generated-contracts.ts";
import { parseBroadPartOfSpeech } from "./generated-decode.ts";

export type ScriptedStep =
  | Result<MaterialProviderResult, MaterialProviderFailure>
  | ((
      request: MaterialProviderRequest,
    ) => Result<MaterialProviderResult, MaterialProviderFailure>);

export const createScriptedMaterialProvider = (
  steps: readonly ScriptedStep[],
): MaterialProvider => {
  let index = 0;
  let last: RedactedProviderRequest | null = null;
  return {
    identity: {
      provider: "scripted",
      model: "deterministic",
      promptVersion: "test-v1",
    },
    inspectLastRequest: () => last,
    generate: async (request) => {
      last = { endpoint: "scripted://learning-material", body: request };
      const step = steps[Math.min(index, steps.length - 1)];
      index += 1;
      if (step === undefined) {
        return { ok: false, error: { kind: "offline", detail: "script exhausted" } };
      }
      return typeof step === "function" ? step(request) : step;
    },
  };
};

const grammarSurface: Readonly<Record<string, string>> = {
  "〜ている": "ている",
  "〜たことがある": "たことがある",
  "〜なければならない": "なければならない",
  "〜てもいい": "てもいい",
  "〜てはいけない": "てはいけない",
  "〜そうだ（様態）": "そうだ",
  "〜かもしれない": "かもしれない",
  "〜ので": "ので",
  "〜のに": "のに",
  "〜ながら": "ながら",
  "〜たり〜たりする": "たりたりする",
  "〜ようになる": "ようになる",
  "〜ことにする": "ことにした",
  "〜つもりだ": "つもりだ",
  "〜たばかりだ": "たばかりだ",
  "〜てしまう（縮約）": "ちゃう",
  可能形: "できる",
  受身形: "られる",
  使役形: "させる",
  "〜ほど〜ない": "ほどでもない",
  "〜前に": "前に",
  "〜ても": "ても",
  // Batch 1: V1 inventory #1-25, keyed by verbatim V1 formalName.
  だ: "だ",
  は: "は",
  も: "も",
  に: "に",
  で: "で",
  を: "を",
  が: "が",
  から: "から",
  まで: "まで",
  と: "と",
  よ: "よ",
  ね: "ね",
  "～んです": "んです",
  の: "の",
  けど: "けど",
  とか: "とか",
  とく: "とく",
  なきゃ: "なきゃ",
  みたい: "みたい",
  これ: "これ",
  それ: "それ",
  あれ: "あれ",
  か: "か",
  ここ: "ここ",
  そこ: "そこ",
  // Batch 2: V1 inventory #26-50, keyed by verbatim V1 formalName.
  あそこ: "あそこ",
  "〜くない": "くない",
  "〜じゃない": "じゃない",
  "〜ない (る-Verb Negative)": "ない",
  "〜ない (う-Verb Negative)": "ない",
  "〜ます": "ます",
  でしょう: "でしょう",
  だろう: "だろう",
  がある: "がある",
  がいる: "がいる",
  この: "この",
  その: "その",
  あの: "あの",
  "〜かった": "かった",
  "の ( nominalizer )": "の",
  する: "する",
  くる: "くる",
  好き: "好き",
  きらい: "きらい",
  のがすき: "のがすき",
  "ので / から": "ので",
  "〜なかった": "なかった",
  "〜て": "て",
  // Batch 3: V1 inventory #51-75 (#68 and #70 already declared above).
  "〜ている (進行)": "ている",
  "〜にいく": "にいく",
  だれ: "だれ",
  "なんで / どうして": "なんで",
  じゃない: "じゃない",
  "〜くなかった": "くなかった",
  って: "って",
  "Verb + Noun": "食べる人",
  "の (省略)": "の",
  な: "な",
  だけ: "だけ",
  どこ: "どこ",
  どれ: "どれ",
  "〜ている (状態)": "ている",
  てから: "てから",
  "もう / まだ": "もう",
  "まだ〜てない": "まだ食べていない",
  "〜たい": "たい",
  けっこう: "けっこう",
  たくさん: "たくさん",
  "くらい / ぐらい": "くらい",
  すぎる: "すぎる",
  にする: "にする",
  // Batch 4: V1 inventory #76-100 (#84 and #88 already declared above).
  "〜になる・〜くなる": "になる",
  "〜のほうが": "のほうが",
  "なにか・なにも": "なにか",
  "誰か・どこか・誰も・どこも": "誰か",
  "〜ましょう / 〜ましょうか": "ましょう",
  "〜ませんか": "ませんか",
  "〜ないでください": "ないでください",
  "〜たほうがいい / 〜ないほうがいい": "たほうがいい",
  "Adjective + て / Noun + で": "高くて",
  "のがへた / のがじょうず": "のがへた",
  "あげる / くれる / もらう": "あげる",
  とき: "とき",
  あとで: "あとで",
  までに: "までに",
  ごろ: "ごろ",
  "〜ていた": "ていた",
  るところだ: "るところだ",
  "〜ていく / 〜てくる": "ていく",
  "〜はじめる": "はじめる",
  "〜おわる": "おわる",
  // Batch 5: V1 inventory #101-125 (#103 and #121 already declared above).
  "〜なおす": "なおす",
  "ないで / なくて": "ないで",
  でも: "でも",
  "れる・られる": "れる",
  ということ: "ということ",
  だけで: "だけで",
  なるべく: "なるべく",
  "〜ら": "ら",
  "だんだん / どんどん": "だんだん",
  とおもう: "とおもう",
  こと: "こと",
  "そう (伝聞・様態)": "そうだ",
  "とか～とか": "本とかペンとか",
  そういう: "そういう",
  "Verb[よう]": "食べよう",
  かな: "かな",
  "ば / なら": "ば",
  "がる / たがる": "寒がる",
  がする: "がする",
  "みたいに・みたいな": "みたいに",
  "そうに・そうな": "そうに",
  "〜ようと思う": "ようと思う",
  "〜にする / 〜くする": "くする",
  // Batch 6: V1 inventory #126-150 (#127 already declared above).
  といい: "といい",
  じゃないか: "じゃないか",
  らしい: "らしい",
  てほしい: "てほしい",
  "聞こえる / 見える": "聞こえる",
  "～代": "バス代",
  "かかる / する (コスト)": "かかる",
  "Number + も": "三人も",
  ほとんど: "ほとんど",
  "そんな・こんな・あんな・どんな": "そんな",
  "以上 / 以外": "以上",
  ずっと: "ずっと",
  だいたい: "だいたい",
  "なん + counter + か": "何人か",
  "真(っ)": "真っ白",
  "Number + しか〜ない": "三人しかいない",
  "すこしも～ない": "すこしも食べない",
  ばあいは: "ばあいは",
  てよかった: "てよかった",
  "Verb［せる・させる］": "食べさせる",
  "〜ても・〜でも": "ても",
  "てしまう / ちゃう": "てしまう",
  させられる: "させられる",
  てある: "てある",
  // Batch 7: V1 inventory #151-175 (#170 already declared above). Earlier
  // surfaces corrected here to detectable stems: bare た/やすい/にくい/づらい
  // never fire without a verb stem.
  "〜た (る)": "食べた",
  "〜た (う)": "書いた",
  "〜やすい": "食べやすい",
  "〜にくい": "食べにくい",
  "〜づらい": "食べづらい",
  ているあいだに: "ているあいだに",
  なくてもいい: "なくてもいい",
  てみる: "てみる",
  "〜てあげる / 〜てくれる / 〜てもらう": "てあげる",
  "〜てくれてありがとう": "てくれてありがとう",
  "〜てくれない / 〜てもらえない": "てくれない",
  たら: "食べたら",
  ほかに: "ほかに",
  そんなに: "そんなに",
  "れる・られる (可能)": "れる",
  "んだけど / んですが": "んだけど",
  "はずだ / はずがない": "はずだ",
  かどうか: "かどうか",
  "と (条件)": "行くと",
  ないと: "ないと",
  だけでなく: "だけでなく",
  かい: "行くかい",
  もし: "もし",
  し: "安いし",
  ようにする: "ようにする",
  "〜つづける": "つづける",
  ようにいう: "ようにいう",
  よていだ: "よていだ",
  "〜たばかり": "たばかり",
  // Batch 8: V1 inventory #176-200.
  "命令形 (動詞)": "書け",
  "ように (目的)": "ように",
  かしら: "かしら",
  って感じ: "って感じ",
  風: "日本風",
  にきがつく: "にきがつく",
  それに: "それに",
  それで: "それで",
  "Question-phrase + か": "だれか",
  それでも: "それでも",
  たらどう: "たらどう",
  といわれている: "といわれている",
  ばよかった: "ばよかった",
  ばいい: "ばいい",
  中: "部屋の中",
  "うちに / ないうちに": "うちに",
  "べき / べきではない": "べきだ",
  なかなか: "なかなか",
  "なかなか〜ない": "なかなか来ない",
  によって: "によって",
  "全く〜ない": "全く知らない",
  させてもらう: "させてもらう",
  "Particle + の": "私の",
  "ところが / ところで": "ところが",
  "ほど / ほど〜ない": "ほど",
  // Batch 9: V1 inventory #201-225.
  "ば〜ほど": "行けば行くほど",
  "という / というのは": "という",
  的: "日本的",
  "もの / もん": "もの",
  ものだ: "ものだ",
  おかげで: "おかげで",
  "こそ / からこそ": "こそ",
  ばかり: "ばかり",
  ばかりに: "ばかりに",
  "ことがある (頻度)": "ことがある",
  "ことにする / ことになる": "ことにする",
  ことはない: "ことはない",
  "～と言っても": "と言っても",
  といえば: "といえば",
  "〜合う": "話し合う",
  について: "について",
  ちゃんと: "ちゃんと",
  に比べて: "に比べて",
  "どんなに〜ても / いくら〜でも": "どんなに高くても",
  かなり: "かなり",
  あまりに: "あまりに寒い",
  "わけだ / わけではない": "わけだ",
  ところだった: "ところだった",
  "だって / んだって": "だって",
  に対して: "に対して",
  // Batch 10: V1 inventory #226-250.
  "さ (フィラー・間投詞)": "いいさ",
  それぞれ: "それぞれ",
  まま: "まま",
  しかない: "しかない",
  "～ても～なくても": "行っても行かなくても",
  んじゃない: "んじゃない",
  わけがない: "わけがない",
  "としたら / とすると": "としたら",
  として: "として",
  にしては: "にしては",
  にしても: "にしても",
  にとって: "にとって",
  というより: "というより",
  はもちろん: "雨はもちろん",
  て初めて: "て初めて",
  "さえ / さえ〜ば": "さえ",
  たものだ: "たものだ",
  さて: "さて",
  むしろ: "むしろ",
  つまり: "つまり",
  かえって: "かえって",
  "〜気がする": "気がする",
  "とても〜ない": "とても寒くない",
  "別に〜ない": "別に食べない",
  じゃなくて: "じゃなくて",
  // Batch 11: V1 inventory #251-275.
  "〜ようとしない": "ようとしない",
  もしかしたら: "もしかしたら",
  "〜かというと": "かというと",
  "〜ずつ": "一つずつ",
  だらけ: "だらけ",
  "〜み": "楽しみ",
  "〜と違って": "と違って",
  に違いない: "に違いない",
  "に限る / とは限らない": "に限る",
  "めったに〜ない": "めったに来ない",
  割に: "割に",
  "Verb[volitional]とする": "行こうとする",
  そうもない: "できそうもない",
  ないことはない: "ないことはない",
  "なんか・なんて": "なんか",
  ついでに: "ついでに",
  たとたんに: "帰ったとたんに",
  "おきに / たびに": "たびに",
  "なし / あり": "なし",
  考えられない: "考えられない",
  "〜向き / 〜向け": "向き",
  "〜切る / 〜きれない": "食べきる",
  "〜きり": "これっきり",
  "〜かけ": "食べかけ",
  "〜たて": "焼きたて",
  // Batch 12: V1 inventory #277-296, completing verbatim V1 coverage.
  "〜込む": "飛び込む",
  ふりをする: "ふりをする",
  "できれば (できたら)": "できれば",
  でよければ: "でよければ",
  とおり: "その通り",
  どうしても: "どうしても",
  同士: "同士",
  まさか: "まさか",
  つい: "ついうっかり",
  せいで: "雨のせいで",
  くせに: "子供のくせに",
  "〜がち / 〜ぎみ": "病気がち",
  "〜っぽい": "子供っぽい",
  "〜っぱなし": "開けっ放し",
  わざわざ: "わざわざ",
  一体: "一体",
  折角: "折角",
  っけ: "だっけ",
  代わりに: "代わりに",
  どころか: "どころか",
  // Batch 11b + tilde-alignment: the skipped V1 #251 plus verbatim names for
  // five original-22 counterparts that carry a 〜 prefix.
  わけにはいかない: "わけにはいかない",
  つもりだ: "つもりだ",
  のに: "のに",
  かもしれない: "かもしれない",
  ようになる: "ようになる",
  ながら: "ながら",
};

const variants = (surface: string, mode: "teach" | "review"): readonly string[] =>
  mode === "teach"
    ? [`${surface}かな。`, `でも${surface}。`, `${surface}だけだ。`]
    : [`${surface}よね。`, `${surface}だって。`, `${surface}かね。`];

export const deterministicMaterialResult = (
  request: MaterialProviderRequest,
): Result<MaterialProviderResult, MaterialProviderFailure> => {
  const content = request.card.content;
  const targetSurface =
    request.card.type === "grammar" && "canonicalForm" in content
      ? (grammarSurface[content.canonicalForm] ??
        content.canonicalForm.replaceAll("〜", "").replaceAll("～", ""))
      : "lemma" in content
        ? content.lemma
        : "";
  const candidates = variants(targetSurface, request.mode).map((japanese) => {
    const start = japanese.indexOf(targetSurface);
    const shared = {
      mode: request.mode,
      context: "Someone is responding naturally in a simple everyday situation.",
      prompt:
        request.mode === "teach"
          ? "Study the highlighted target."
          : "What does the target express?",
      japanese,
      targetSurface,
      targetSpan: {
        start,
        end: start + targetSurface.length,
        unit: "utf16-code-unit" as const,
        normalization: "nfkc-v1" as const,
      },
      readingSegments: [{ written: japanese, reading: "" }],
      answer: content.meaning,
      explanation: content.usageNotes || content.meaning,
      usageNote: content.usageNotes || "Use it in an appropriate everyday context.",
    };
    return request.card.type === "grammar" && "canonicalForm" in content
      ? {
          ...shared,
          targetKind: "grammar" as const,
          target: {
            canonicalForm: content.canonicalForm,
            meaning: content.meaning,
            formationHint: content.formation,
          },
        }
      : {
          ...shared,
          targetKind: "vocabulary" as const,
          target: {
            lemma: "lemma" in content ? content.lemma : "",
            reading: "reading" in content ? content.reading : "",
            partOfSpeech:
              ("partOfSpeech" in content
                ? parseBroadPartOfSpeech(content.partOfSpeech)
                : null) ?? "noun",
            meaning: content.meaning,
          },
        };
  });
  return ok({
    requestId: `scripted-${request.card.id}-${request.mode}`,
    candidates,
    provider: "scripted",
    model: "deterministic",
    promptVersion: "test-v1",
  });
};

export const createDeterministicMaterialProvider = (): MaterialProvider =>
  createScriptedMaterialProvider([deterministicMaterialResult]);
